"""add password hash

Revision ID: 77a360f1defa
Revises: 
Create Date: 2024-03-16 00:09:37.672209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a360f1defa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_model', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
